### ISSUE TITLE
port forwarding fails when service port is using a named target port

### ISSUE THREAD

**Issue by sgandon** [txn2/kubefwd#13]
When a service is defined using a named target port like this
```
apiVersion: v1
kind: Service
metadata:
  name: streamsoss
spec:
  ports:
  - name: http-port
    port: 80
    targetPort: service-port
```
The port forwarding fails whereas if the targetPort is an hardcoded integer it works.
