### ISSUE TITLE
use with docker-compose

### ISSUE THREAD

**Issue by jeff1985** [txn2/kubefwd#131]
I have seen that you provide instructions to run kubefwd with docker. Is it also possible to use it with docker-compose and do you have an example?

**Comment by boedy** [comment]
Hey @jeff1985 . I had the same question, so I started playing around with it. Here is how I currently use it.

```
version: "2"
services:
  kubefwd:
    image: txn2/kubefwd
    volumes:
      - /Users/<username>/.kube/:/root/.kube/
    command: "svc -n default"
    privileged: true
  nginx:
    image: nginx:1.9
    ports:
      - "80:80"
    links:
      - kubefwd:php
    volumes_from:
      - php
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    image: php:latest
    network_mode: service:kubefwd
    volumes:
      - ./:/var/www/html
```
