### ISSUE TITLE
Add port forward for pods

### ISSUE THREAD

**Issue by wazowsk1** [txn2/kubefwd#138]
Is is possible to add support for forwarding to pods?

In my usecase I have a statefulset with 2 replicas, and I need to port forward to both pods in addition to services.

**Comment by cjimti** [comment]
@wazowsk1 1.17.0 will forward the individual pods names as well as the service if you have a headless service. 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: ok-ss-headless
  namespace: kf-a
spec:
  selector:
    app: ok-ss
    component: ss
  ports:
    - name: http-web
      protocol: "TCP"
      port: 8080
      targetPort: http-web
    - name: http-web2
      protocol: "TCP"
      port: 8081
      targetPort: http-web2
  type: ClusterIP
  clusterIP: None
```
