### ISSUE TITLE
Port forward headless services used by sts but with clusterip

### ISSUE THREAD

**Issue by leelavg** [txn2/kubefwd#194]
First of all, thanks a lot for this lean and mean tool to get work done.

## Assume we have below setup:
1. A service with `selector` and `type: ClusterIP` is created, let's say service name is `serv-a`
2. We have sts using this service `serv-a`  by specifying `serviceName: serv-a` and so each pod can be accessed by both DNS query like `http://<podname>.<svcname>.<ns>.svc:<port>` and status of sts can be found hitting the clusterIP like `serv-a/status`

I'm on `kubefwd version: 1.20.0`

### Current state:
- When we use kubefwd, it'll forward only the clusterip, meaning one pod is accessible
- Since clusterip is **not None**, kubefwd isn't forwarding all pods behind `serv-a` which when done we can resolve each pod by dns name

### Expected enhancement:
- Provide an option to state clusterIP as None even if we have one, in that scenario we can have all pods behind `serv-a` can be resolvable by dns

Is it possible at all? If k8s doesn't support it, how tough it'll be for kubefwd to construct these dns name on the fly and fill up the /etc/hosts?

PS: I really don't have a way to change the prebuilt app and so raising this issue whether it can be implementable or not.

Thanks.

**Comment by cjimti** [comment]
@leelavg `kubefwd` is able to forward headless services with no ClusterIP as long as there is a selector.

Example
```
apiVersion: v1
kind: Service
metadata:
  labels:
    v1.min.io/tenant: demo
  name: demo-hl
  namespace: demo
spec:
  clusterIP: None
  ports:
  - name: http-minio
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    v1.min.io/tenant: demo
  sessionAffinity: None
  type: ClusterIP

```
Kubefwd:

```     
INFO[13:20:43] Port-Forward: 127.1.27.1 demo-hl:9000 to pod demo-ss-0-0:9000 
INFO[13:20:43] Port-Forward: 127.1.27.2 demo-ss-0-0.demo-hl:9000 to pod demo-ss-0-0:9000 
INFO[13:20:43] Port-Forward: 127.1.27.3 demo-ss-0-1.demo-hl:9000 to pod demo-ss-0-1:9000 
INFO[13:20:43] Port-Forward: 127.1.27.4 demo-ss-0-2.demo-hl:9000 to pod demo-ss-0-2:9000 
INFO[13:20:43] Port-Forward: 127.1.27.5 demo-ss-0-3.demo-hl:9000 to pod demo-ss-0-3:9000 
```
