### ISSUE TITLE
unknown command "oidc-login" for "kubectl"

### ISSUE THREAD

**Issue by moafak** [txn2/kubefwd#246]
Hi,
I'm running on linux, trying to run kubefwd with:
`sudo -E kubefwd svc -c $KUBECONFIG -n default`

Getting the error:

```
error: unknown command "oidc-login" for "kubectl"
FATA[17:16:59] Error connecting to k8s cluster: Get "https://(REDACTED)": getting credentials: exec: executable kubectl failed with exit code 1
```

My cubeconfig looks similar to this:
```
current-context: (REDACTED)
kind: Config
preferences: {}
users:
- name: (REDACTED)
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=(REDACTED)
      - --oidc-client-id=(REDACTED)
      - --oidc-extra-scope=profile,groups
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

P.S:  `kubectl` works fine without `kubefwd`
