### ISSUE TITLE
config file option with -z doesn't work

### ISSUE THREAD

**Issue by rauerhans** [txn2/kubefwd#284]
like at all

`❯ sudo -E kubefwd services -z kubefwd.yaml`

```
baseUnreservedIP: 127.1.28.1
serviceConfigurations:
  - name: kind-argocd-server.argocd
    ip: 127.1.28.2
  - name: kind-minio-console.minio
    ip: 127.1.28.3

```

works nicely without it but I'd like to have file config
