### ISSUE TITLE
kubefwd does not work for ClusterIP without any selectors

### ISSUE THREAD

**Issue by goodhoko** [txn2/kubefwd#35]
We have a service of ClusterIP type without any selectors (backed by manual Endpoint) which is defined as so:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: prod
spec:
  ports:
  - name: http
    protocol: TCP
    port: 9200
    targetPort: 9200
---
kind: Endpoints
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: prod
subsets:
  - addresses:
      - ip: 10.132.0.6
    ports:
      - name: http
        port: 9200
        protocol: TCP
```

When trying to access it thru kubefwd it fails with:
```
2019/01/07 18:41:40 Runtime error: an error occurred forwarding 9200 -> 9200: error forwarding port 9200 to pod d3dd8d6c2ccd2f3576689afe4868cc30a6a4394cff74e97a8ea1dbabb407da0b, uid : exit status 1: 2019/01/07 17:41:40 socat[39057] E connect(5, AF=2 127.0.0.1:9200, 16): Connection refused
```
Forwarding to all the other services backed by pods works ok.

Accessing the service from withing the cluster also works just fine:
```bash
root@some_other_pod_in_the_cluster:/usr/local/tomcat# curl -v elasticsearch:9200/
*   Trying 10.15.254.34...
* TCP_NODELAY set
* Connected to elasticsearch (10.15.254.34) port 9200 (#0)
> GET / HTTP/1.1
> Host: elasticsearch:9200
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 493
...
```
// The 10.15.254.34 IP is indeed the one allocated to the `elasticsearch` service.

I hope I provided enough info. Thanks for your time.

Best.

**Comment by cjimti** [comment]
Looks like it needs to find endpoints without selectors. I'll try to take a look at it this week. Thanks for the report.

**Comment by cjimti** [comment]
More thought needs to be put into this on my end. At the moment Kubefwd only port-forwards to Pods, however, services could very well be pointing to anything, even an external IP address. Does it seem like I would need to create a local reverse proxy for services that do not point me to Pods? In my clusters, we use Pod selectors for all of our services so I don't have a lot of experience in this area and could be misunderstanding the problem.

**Comment by lumberj** [comment]
Same case here. In my case, I'm using an `ExternalName` to point to an RDS server,

```
2019/02/11 13:07:49 Runtime error: an error occurred forwarding 3306 -> 3306: error forwarding port 3306 to pod 12def1bc08d1df9342824e6dfb658ea7b5af6d9e95dfc733853f2ae7cea9acef, uid : exit status 1: 2019/02/11 21:07:49 socat[10037] E connect(5, AF=2 127.0.0.1:3306, 16): Connection refused
```

Service looks like:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  externalName: rds-db.us-east-1.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: ExternalName
```

**Comment by cjimti** [comment]
I am open to suggestions on how to implement this. Kubefwd finds Pods connected to a Service and uses the Kubernetes API: create-connect-portforward. 

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#create-connect-portforward

I probably need to research create-connect-proxy on the Service API. 

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#create-connect-proxy-182

If anyone has with experience with this I would appreciate a pointing in the right direction. 

My schedule is a bit packed the next few weeks but I am trying to get a few of these enhancements on the radar as well as some bug fixes.

**Comment by lumberj** [comment]
I ended up doing something like this.

I created an ExternalName service as above,

```
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: my-namespace
  labels:
    app: mysql
spec:
  externalName: rds-db.us-east-1.rds.amazonaws.com
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  type: ExternalName
```

Then I ran a temporary deployment + service in the same namespace,

```
kubectl --namespace my-namespace run mysql-tunnel-$USER \
    -it --image=alpine/socat \
    --tty --rm --expose=true --port=3306 \
    tcp-listen:3306,fork,reuseaddr tcp-connect:mysql:3306
```

And proxied to that,

```
kubectl -n my-namespace port-forward svc/mysql-tunnel-$USER 3306:3306
```
